Traceback (most recent call last):
  File "D:\FROM_CAP_TO_GMAO\Altair_V2.py", line 127, in getEquipLoc
    equipment={"codeequipment": equip["codeequipment"], "description": equip["description"], "fkcodeequipment" : equip.get("fkcodeequipment"), "fkcodelocation" : equip["fkcodelocation"]}
KeyError: 'fkcodelocation'
